version: '3'

services:
  embl_redis:
    container_name: embl_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - ./config/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    container_name: app_server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4
    volumes:
      - .:/app
    expose:
      - "8080"